apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: "simple-game-server-"
spec:
  ports:
  - name: default
    portPolicy: Dynamic
    containerPort: 7654
  template:
    spec:
      tolerations:
      - key: "agones.dev/agones-system"
        operator: "Equal"
        value: "true"
        effect: "NoExecute"    
      containers:
      - name: simple-game-server
        image: gcr.io/agones-images/simple-game-server:0.2
        resources:
          requests:
            memory: "64Mi"
            cpu: "20m"
          limits:
            memory: "64Mi"
            cpu: "20m"
      nodeSelector:
        agentpool: agonesnp2